# 2025-08-01, 김병현 수정 - Nginx Reverse Proxy 추가 및 포트 설정 변경
services:
  # Nginx Reverse Proxy 서비스
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"  # 외부 접근은 nginx로만
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - frontend
      - cms
      - backend
    networks:
      - app-network
    restart: unless-stopped

  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: myapp
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app-network
    restart: unless-stopped

  # 백엔드 서비스 (NestJS)
  backend:
    build:
      context: ../back-end
      dockerfile: Dockerfile
    expose:
      - "3000"  # 내부 네트워크에서만 접근 가능
    environment:
      - NODE_ENV=production
    depends_on:
      - postgres
    networks:
      - app-network
    restart: unless-stopped

  # 프론트엔드 서비스 (React + Vite + Nginx)
  frontend:
    build:
      context: ../front-end
      dockerfile: Dockerfile
    expose:
      - "80"  # 내부 네트워크에서만 접근 가능
    depends_on:
      - backend
    networks:
      - app-network
    restart: unless-stopped

  # CMS 서비스 (React + Vite + Nginx)
  cms:
    build:
      context: ../cms-admin
      dockerfile: Dockerfile
    expose:
      - "80"  # 내부 네트워크에서만 접근 가능
    depends_on:
      - backend
    networks:
      - app-network
    restart: unless-stopped

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge
